### ISSUE TITLE
sort nazonazo in russian

### ISSUE THREAD

**Issue by fabon-f** [LoliGothick/sort_nazonazo_rs#4]
Sorry, I'm not good at English.

Я увлекаюсь Назоназом Сортировки, и хочу играть в него на русском языке. У меня есть русский словарь, но я совсем не умею писать код на Rust.

Я потом сделаю pull request, который добавит русский словарь. Буду очень признателен, если бы вы смогли принять мой pull request.

**Comment by loliGothicK** [comment]
#6

**Comment by loliGothicK** [comment]
Done,
Thanks!
